In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.metrics import confusion_matrix
y_true = ["Rainy", "Sunny", "Sunny", "Rainy", "Sunny", "Rainy"]
y_pred = ["Sunny", "Sunny", "Rainy", "Rainy", "Sunny", "Sunny"]
confusion_matrix(y_true, y_pred, labels=["Rainy", "Sunny"])

array([[1, 2],
       [1, 2]])

In [ ]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=10, n_features=3)
from sklearn.model_selection import LeavePOut
lpo = LeavePOut(p=2)
count=0
for train, test in lpo.split(X):
    print(train, test)
    count+=1
print(count)

[2 3 4 5 6 7 8 9] [0 1]
[1 3 4 5 6 7 8 9] [0 2]
[1 2 4 5 6 7 8 9] [0 3]
[1 2 3 5 6 7 8 9] [0 4]
[1 2 3 4 6 7 8 9] [0 5]
[1 2 3 4 5 7 8 9] [0 6]
[1 2 3 4 5 6 8 9] [0 7]
[1 2 3 4 5 6 7 9] [0 8]
[1 2 3 4 5 6 7 8] [0 9]
[0 3 4 5 6 7 8 9] [1 2]
[0 2 4 5 6 7 8 9] [1 3]
[0 2 3 5 6 7 8 9] [1 4]
[0 2 3 4 6 7 8 9] [1 5]
[0 2 3 4 5 7 8 9] [1 6]
[0 2 3 4 5 6 8 9] [1 7]
[0 2 3 4 5 6 7 9] [1 8]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 3 5 6 7 8 9] [2 4]
[0 1 3 4 6 7 8 9] [2 5]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 5 6 7 8 9] [3 4]
[0 1 2 4 6 7 8 9] [3 5]
[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 4 5 6 8 9] [3 7]
[0 1 2 4 5 6 7 9] [3 8]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 5 7 8 9] [4 6]
[0 1 2 3 5 6 8 9] [4 7]
[0 1 2 3 5 6 7 9] [4 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 3 4 7 8 9] [5 6]
[0 1 2 3 4 6 8 9] [5 7]
[0 1 2 3 4 6 7 9] [5 8]
[0 1 2 3 4 6 7 8] [5 9]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 7 9] [6 8]
[0 1 2 3 4 5 7 8

In [6]:
X = ['a', 'b', 'c', 'd', 'e', 'f']
from sklearn.model_selection import RepeatedKFold
rkf = RepeatedKFold(n_splits=3, n_repeats=2, random_state=10)
for train, test in rkf.split(X):
    print(train, test)

[0 1 3 4] [2 5]
[1 2 4 5] [0 3]
[0 2 3 5] [1 4]
[1 3 4 5] [0 2]
[0 2 3 4] [1 5]
[0 1 2 5] [3 4]


In [8]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
pipe = ([
    ('scaler', StandardScaler()),
    ('softmax', LogisticRegression(multi_class='multinomial'))
])

In [9]:
from sklearn.metrics import f1_score
y_true = [1,1,0,1,0,0,1,0,1]
y_pred = [0,1,0,1,0,1,1,1,1]
print(f1_score(y_pred, y_true))

0.7272727272727273


In [12]:
from sklearn.svm import SVC
# clf = SVC(C=1).fit(X_train, y_train)
# print(clf.support_) 
# prints array of support vectors

In [ ]:
from sklearn.neighbors import NearestNeighbors
neigh = NearestNeighbors(n_neighbors=1)
neigh.fit(X_train)
print(neigh.kneighbors(X_test[1:2, :]))

In [13]:
from sklearn.datasets import make_regression
from sklearn.preprocessing import PolynomialFeatures
X, y = make_regression(n_samples=10, n_features=3)
poly_transform = PolynomialFeatures(degree=2, interaction_only=True)
X_trans = poly_transform.fit_transform(X)
print(X_trans.shape)

(10, 7)


In [14]:
X = ['a', 'b', 'c ', 'd', 'e', 'f', 'g', 'h', 'i']
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
for train, test in kf.split(X):
    print(train, test)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [15]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['This is the first document.', 'This document is the second document.']
vectorizer = CountVectorizer()
vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())

['document' 'first' 'is' 'second' 'the' 'this']


In [17]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=10, n_features=2)
from sklearn.preprocessing import PolynomialFeatures
poly_transform = PolynomialFeatures(degree=2, interaction_only=True)
X_trans = poly_transform.fit_transform(X)
print(X_trans.shape)

(10, 4)


In [20]:
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
X, y = load_wine(as_frame=True, return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=12)
clf = DecisionTreeClassifier(max_depth=5, min_samples_split=2, min_samples_leaf=3, random_state=81)
clf.fit(X_train, y_train)
print(clf.score(X_train, y_train))


0.9875


In [21]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid = [{'max_depth': range(1,10,2), 'min_samples_split': range(1,10,3)}]
gs = GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5)
gs.fit(X,y)

c:\Users\KIIT0001\OneDrive\Desktop\mlpractice\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
25 fits failed out of a total of 75.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\KIIT0001\OneDrive\Desktop\mlpractice\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KIIT0001\OneDrive\Desktop\mlpractice\.venv\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\KIIT0

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid=[{'max_depth': range(1, 10, 2),
                          'min_samples_split': range(1, 10, 3)}])

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
lin_reg=LinearRegression()
shuffle_split=ShuffleSplit(n_splits=5, test_size=0.2, random_state=42)
score=cross_val_score(lin_reg, X, y, cv=shuffle_split, scoring='neg_mean_absolute_error')

In [26]:
from sklearn.metrics import max_error
y_true=[0.5,0.2,0.7,1]
y_pred=[0.4,0.2,1,0.1]
max_error(y_true,y_pred)

0.9

In [2]:
from sklearn.preprocessing import MaxAbsScaler
a = [[-3],[0],[-2],[2],[-1],[-4]]
max = MaxAbsScaler()
scaled_a = max.fit_transform(a)
print(scaled_a.max())

0.5


In [3]:
y_train = [['regular', 'veg'], ['medium', 'veg'], ['regular', 'non-veg'], ['medium', 'non-veg']]
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer(classes=['regular', 'medium', 'veg', 'non-veg'])
print(mlb.fit_transform(y_train))

[[1 0 1 0]
 [0 1 1 0]
 [1 0 0 1]
 [0 1 0 1]]


In [4]:
corpus = ['An overfitted model is a mathematical model that contains more parameters that can be justified by the data.']
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectors = vectorizer.fit_transform(corpus)
print(vectors.shape)

(1, 15)


In [5]:
from sklearn.preprocessing import LabelEncoder
data = ["apple", "orange", "banana", "apple", "grape", "orange", "grape"]
encoder = LabelEncoder()
encoded_data = encoder.fit_transform(data)
print(encoded_data)

[0 3 1 0 2 3 2]


In [6]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler, Binarizer
data = [[1,5], [5,15], [0,10], [1,15]]
pipeline = Pipeline([('scaler', MinMaxScaler()), ('binarizer', Binarizer(threshold=0.1))])
transformed_data = pipeline.fit_transform(data)
print(transformed_data)

[[1. 0.]
 [1. 1.]
 [0. 1.]
 [1. 1.]]


In [7]:
data = [[1,3], [2,4]]
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=3, interaction_only=False)
print(pf.fit_transform(data))

[[ 1.  1.  3.  1.  3.  9.  1.  3.  9. 27.]
 [ 1.  2.  4.  4.  8. 16.  8. 16. 32. 64.]]


In [8]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
X=np.array([1,2,3,4,5])
X=X.reshape(-1,1)
poly=PolynomialFeatures(degree=3)
X_poly=poly.fit_transform(X)
print(X_poly.shape)

(5, 4)


In [11]:
from sklearn.linear_model import Perceptron
X = [[0,0.5], [1,1.5], [1,2], [2,3]]
y= [-1,-1,1,1]
clf = Perceptron(tol=None, shuffle=False, random_state=42)
clf.fit(X, y)
iterations = clf.n_iter_
print(iterations)

1000


In [14]:
from sklearn.neighbors import KNeighborsClassifier
X = [[2,3], [5,6], [10,11], [15,16], [20,21]]
y = [2,2,0,1,0]
knn = KNeighborsClassifier(n_neighbors=3, metric='euclidean', weights='uniform')
knn.fit(X,y)
print(knn.predict([[8,9]]))

[2]


In [16]:
import numpy as np
from sklearn.impute import SimpleImputer
data = [[5,8,4],[8,4,1],[7,np.nan,6],[4,2,3],[np.nan,6,6]]
si = SimpleImputer(missing_values=np.nan, strategy="mean")
si.fit(data)
print(si.statistics_)

[6. 5. 4.]


In [ ]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
X = np.array([1,2,3,4])
X = X.reshape(-1,2)
poly = PolynomialFeatures(degree=3)
X_poly = poly.fit_transform(X)
print(X_poly.shape)

[[1 2]
 [3 4]]
(2, 10)


In [20]:
from sklearn import linear_model
clf = linear_model.Lasso(alpha=0.1)
clf.fit([[1,2],[2,1],[2,3]],[1,2,3])
linear_model.Lasso(alpha=0.1,max_iter=1000,tol=0.0001,warm_start=False, fit_intercept=True)
print(clf.coef_)

[1.05 0.35]


In [21]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[5,4],[5,6],[10,8],[10,12]])
kmens = KMeans(n_clusters=2, random_state=0).fit(X)
kmens.labels_

array([1, 1, 0, 0], dtype=int32)

In [23]:
from sklearn.datasets import load_iris
from sklearn.linear_model import SGDClassifier

X, y = load_iris(return_X_y=True)
clf = SGDClassifier(random_state=0).fit(X, y)

print(y[70:80])
# print(clf.predict(X[70:80, :]))
# print(clf.score(X[70:80, :], y[70:80]))


[1 1 1 1 1 1 1 1 1 1]


In [24]:
from sklearn.neighbors import KNeighborsClassifier
X_train = [[1,100],[4,400],[5,500],[6,600],[8,800],[9,900],[11,1100],[12,1200],[15,1500],[18,1800],[19,1900]]
y_train  = [2,2,2,2,2,2,2,2,1,1,1]
X_test = [[2,200]]
knn = KNeighborsClassifier(n_neighbors=7, metric="euclidean", weights='uniform')
knn.fit(X_train, y_train)
print(knn.predict(X_test))

[2]


In [25]:
from sklearn.neighbors import KNeighborsClassifier
X_train = [[1,2],[3,4],[5,6]]
y_train = [0,1,2]
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)
print(len(knn.classes_))

3


In [ ]:
from sklearn.linear_model import SGDRegressor
sgd = SGDRegressor(SH)