In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.metrics import confusion_matrix
y_true = ["Rainy", "Sunny", "Sunny", "Rainy", "Sunny", "Rainy"]
y_pred = ["Sunny", "Sunny", "Rainy", "Rainy", "Sunny", "Sunny"]
confusion_matrix(y_true, y_pred, labels=["Rainy", "Sunny"])

array([[1, 2],
       [1, 2]])

In [ ]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=10, n_features=3)
from sklearn.model_selection import LeavePOut
lpo = LeavePOut(p=2)
count=0
for train, test in lpo.split(X):
    print(train, test)
    count+=1
print(count)

[2 3 4 5 6 7 8 9] [0 1]
[1 3 4 5 6 7 8 9] [0 2]
[1 2 4 5 6 7 8 9] [0 3]
[1 2 3 5 6 7 8 9] [0 4]
[1 2 3 4 6 7 8 9] [0 5]
[1 2 3 4 5 7 8 9] [0 6]
[1 2 3 4 5 6 8 9] [0 7]
[1 2 3 4 5 6 7 9] [0 8]
[1 2 3 4 5 6 7 8] [0 9]
[0 3 4 5 6 7 8 9] [1 2]
[0 2 4 5 6 7 8 9] [1 3]
[0 2 3 5 6 7 8 9] [1 4]
[0 2 3 4 6 7 8 9] [1 5]
[0 2 3 4 5 7 8 9] [1 6]
[0 2 3 4 5 6 8 9] [1 7]
[0 2 3 4 5 6 7 9] [1 8]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 3 5 6 7 8 9] [2 4]
[0 1 3 4 6 7 8 9] [2 5]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 5 6 7 8 9] [3 4]
[0 1 2 4 6 7 8 9] [3 5]
[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 4 5 6 8 9] [3 7]
[0 1 2 4 5 6 7 9] [3 8]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 5 7 8 9] [4 6]
[0 1 2 3 5 6 8 9] [4 7]
[0 1 2 3 5 6 7 9] [4 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 3 4 7 8 9] [5 6]
[0 1 2 3 4 6 8 9] [5 7]
[0 1 2 3 4 6 7 9] [5 8]
[0 1 2 3 4 6 7 8] [5 9]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 7 9] [6 8]
[0 1 2 3 4 5 7 8

In [6]:
X = ['a', 'b', 'c', 'd', 'e', 'f']
from sklearn.model_selection import RepeatedKFold
rkf = RepeatedKFold(n_splits=3, n_repeats=2, random_state=10)
for train, test in rkf.split(X):
    print(train, test)

[0 1 3 4] [2 5]
[1 2 4 5] [0 3]
[0 2 3 5] [1 4]
[1 3 4 5] [0 2]
[0 2 3 4] [1 5]
[0 1 2 5] [3 4]


In [8]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
pipe = ([
    ('scaler', StandardScaler()),
    ('softmax', LogisticRegression(multi_class='multinomial'))
])

In [9]:
from sklearn.metrics import f1_score
y_true = [1,1,0,1,0,0,1,0,1]
y_pred = [0,1,0,1,0,1,1,1,1]
print(f1_score(y_pred, y_true))

0.7272727272727273


In [12]:
from sklearn.svm import SVC
# clf = SVC(C=1).fit(X_train, y_train)
# print(clf.support_) 
# prints array of support vectors

In [ ]:
from sklearn.neighbors import NearestNeighbors
neigh = NearestNeighbors(n_neighbors=1)
neigh.fit(X_train)
print(neigh.kneighbors(X_test[1:2, :]))

In [13]:
from sklearn.datasets import make_regression
from sklearn.preprocessing import PolynomialFeatures
X, y = make_regression(n_samples=10, n_features=3)
poly_transform = PolynomialFeatures(degree=2, interaction_only=True)
X_trans = poly_transform.fit_transform(X)
print(X_trans.shape)

(10, 7)


In [14]:
X = ['a', 'b', 'c ', 'd', 'e', 'f', 'g', 'h', 'i']
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
for train, test in kf.split(X):
    print(train, test)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [15]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['This is the first document.', 'This document is the second document.']
vectorizer = CountVectorizer()
vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())

['document' 'first' 'is' 'second' 'the' 'this']


In [17]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=10, n_features=2)
from sklearn.preprocessing import PolynomialFeatures
poly_transform = PolynomialFeatures(degree=2, interaction_only=True)
X_trans = poly_transform.fit_transform(X)
print(X_trans.shape)

(10, 4)
