In [5]:
# Import the PyTorch library
# PyTorch is the primary library for tensor operations and deep learning
import torch

# Display the PyTorch version
# This is crucial for ensuring compatibility with code examples
# Different PyTorch versions may have slight API differences
print(f"PyTorch Version: {torch.__version__}")

PyTorch Version: 2.8.0+cpu


In [6]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
print(f"Numpy version: {np.__version__}")
print(f"Matplotlib version: {matplotlib.__version__}")

Numpy version: 2.3.3
Matplotlib version: 3.10.7


In [7]:
# Check if CUDA (GPU support) is available
print(f"CUDA available: {torch.cuda.is_available()}")

# If CUDA is available, display information about the GPU
if torch.cuda.is_available():
    print(f"Current CUDA device: {torch.cuda.current_device()}")
    print(f"Device name: {torch.cuda.get_device_name(0)}")
    print(f"Device capabilities: CUDA {torch.cuda.get_device_capability(0)}")
    print(f"Device properties: {torch.cuda.get_device_properties(0)}")


CUDA available: False


In [8]:
import torch
import numpy as np
print(f"Pytorch Version: {torch.__version__}")

Pytorch Version: 2.8.0+cpu


In [9]:
scalar_tensor = torch.tensor(7) #Scalar(0-d)
vector_tensor = torch.tensor([1,2,3,4,5]) #vector(1-d)
matrix_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) #matrix(2-d)
tensor_3d = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f"Scalar: {scalar_tensor}, shape: {scalar_tensor.shape}, dimensions: {scalar_tensor.dim()}")
print(f"Vector: {vector_tensor}, shape: {vector_tensor.shape}, dimensions: {vector_tensor.dim()}")
print(f"Matrix: {matrix_tensor}, shape: {matrix_tensor.shape}, dimensions: {matrix_tensor.dim()}")
print(f"3d tensor: {tensor_3d}, shape: {tensor_3d.shape}, dimensions: {tensor_3d.dim()}")

Scalar: 7, shape: torch.Size([]), dimensions: 0
Vector: tensor([1, 2, 3, 4, 5]), shape: torch.Size([5]), dimensions: 1
Matrix: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), shape: torch.Size([3, 3]), dimensions: 2
3d tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]), shape: torch.Size([2, 2, 2]), dimensions: 3


In [10]:
float_tensor = torch.tensor([1.0,2.0])

In [11]:
# Create tensors with specified data types

# Float tensor (default is float32)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

# Double-precision float tensor
double_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

# Integer tensor
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

# Long integer tensor
long_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)

# Boolean tensor
bool_tensor = torch.tensor([1, 0, 1], dtype=torch.int32)

# Print data types and memory usage
print(f"Float32 tensor: {float_tensor.dtype}, bytes per element: {float_tensor.element_size()}")
print(f"Float64 tensor: {double_tensor.dtype}, bytes per element: {double_tensor.element_size()}")
print(f"Int32 tensor: {int_tensor.dtype}, bytes per element: {int_tensor.element_size()}")
print(f"Int64 tensor: {long_tensor.dtype}, bytes per element: {long_tensor.element_size()}")
print(f"Boolean tensor: {bool_tensor.dtype}, bytes per element: {bool_tensor.element_size()}")


Float32 tensor: torch.float32, bytes per element: 4
Float64 tensor: torch.float64, bytes per element: 8
Int32 tensor: torch.int32, bytes per element: 4
Int64 tensor: torch.int64, bytes per element: 8
Boolean tensor: torch.int32, bytes per element: 4


In [13]:
np_array = np.array([[1,2,3],[4,5,6]])
tensor_from_numpy = torch.from_numpy(np_array)
print(f"numpy array:\n{np_array}\ndtype: {np_array.dtype}")
print(f"pytorch tensor from numpy:\n{tensor_from_numpy}\ndtype: {tensor_from_numpy.dtype}")
np_array[0,0] = 100
print(f"\nafter modifying numpy array:")
print(f"numpy array:\n{np_array}")
print(f"pytorch tensor:\n{tensor_from_numpy}")

numpy array:
[[1 2 3]
 [4 5 6]]
dtype: int64
pytorch tensor from numpy:
tensor([[1, 2, 3],
        [4, 5, 6]])
dtype: torch.int64

after modifying numpy array:
numpy array:
[[100   2   3]
 [  4   5   6]]
pytorch tensor:
tensor([[100,   2,   3],
        [  4,   5,   6]])


In [ ]:
zeros_tensor = torch.zeros(3,3)
ones_tensor = torch.ones(2,4)
empty_tensor = torch.empty(2,4) #wharever values are in memory
filled_tensor = torch.full((3,2), 42)
print(f"zeros tensor:\n{zeros_tensor}")
print(f"ones tensor:\n{ones_tensor}")
print(f"empty tensor:\n{empty_tensor}")
print(f"tensor filled with 42:\n{filled_tensor}")

zeros tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
ones tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
empty tensor:
tensor([[2.0783e+00, 1.9156e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor filled with 42:
tensor([[42, 42],
        [42, 42],
        [42, 42]])


In [19]:
import torch

# create a tensor
tensor = torch.tensor([1, 2, 3, 4, 5])

# now multiply it by 10
result = torch.multiply(tensor, 10)

print(result)
print(f"vector tensor:{tensor}")

tensor([10, 20, 30, 40, 50])
vector tensor:tensor([1, 2, 3, 4, 5])
