In [2]:
import torch
x = torch.arange(1., 8)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [4]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [5]:
z=x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [7]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
x_original =torch.rand(size=(224,224,3))
#This format is called HWC (Height, Width, Channels) — commonly used in image libraries like OpenCV or NumPy.
x_permuted = x_original.permute(2,0,1)
print(f"previous shape: {x_original.shape}")
print(f"new:{x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
new:torch.Size([3, 224, 224])


In [12]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [13]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,2]
#There are 3 dimensions:
# 1st : → take all rows (height = 224)
# 2nd : → take all columns (width = 224)
# 2 → take only the 3rd channel (index starts at 0)

tensor([[3, 6, 9]])

In [17]:
import numpy as np
array = np.arange(1.0,8.)
tensor = torch.from_numpy(array)
array, tensor, tensor.shape

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.Size([7]))

In [19]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, numpy_tensor.shape, tensor.shape

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 (7,),
 torch.Size([7]))

shape mismatches
datatype incompatibilty
device mismatch
