In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('Preprocessing1.csv')

In [6]:
avg_price = df['Price'].mean()
print(round(avg_price, 2))

9027.9


In [7]:
month_counts = df['Month'].value_counts()
highest=month_counts.idxmax()
print(highest)

5


In [9]:
weekends = ['Saturday', 'Sunday']
weekend_avg = df[df['WeekDay'].isin(weekends)]['Price'].mean()
weekday_avg = df[~df['WeekDay'].isin(weekends)]['Price'].mean()
print("Weekend Avg:", round(weekend_avg, 2))
print("Weekday Avg:", round(weekday_avg, 2))

Weekend Avg: 9058.02
Weekday Avg: 9015.22


In [10]:
df['Additional_Info'] = df['Additional_Info'].replace('No Info', 'No info')
count = df[(df['Airline'] == 'IndiGo') & (df['Additional_Info'] == 'No info')].shape[0]
print(count)

1650


In [11]:
def duration_to_seconds(x):
    x = x.strip()
    hours, minutes = 0, 0
    if 'h' in x:
        hours = int(x.split('h')[0])
        x = x.split('h')[1]
    if 'm' in x:
        minutes = int(x.replace('m', '').strip()) if x.replace('m', '').strip() != '' else 0
    return hours * 3600 + minutes * 60

df['Duration_seconds'] = df['Duration'].apply(duration_to_seconds)

# Calculate average duration
avg_duration = df['Duration_seconds'].mean()
print("Average flight duration (in seconds):", round(avg_duration, 2))

Average flight duration (in seconds): 38957.94



Apply the following functions to the columns Dep_Time and Arrival_Time:

Transform the values in the 'dep_time' and 'arrival_time' columns to represent the hour component. For instance, if an entry is 10:05 June 13 or 10:05, the corresponding value should be 10. 
Then convert the time into four categories as follows:
5 <= hour < 12 = Morning 
12 <= hour < 17 = Afternoon 
17 <= hour < 20 = Evening 
20 <= hour < 5 = Night

Note: Please ensure that you make the changes directly within the dataset and continue to use that modified dataset for subsequent questions.

How many flights started in the Morning and arrived the destination at Evening?

In [12]:
def extract_hour(t):
    # Handle both "HH:MM" and "HH:MM June 13" formats
    hour_str = str(t).split(':')[0]
    return int(hour_str)

# Apply to both columns
df['Dep_Time'] = df['Dep_Time'].apply(extract_hour)
df['Arrival_Time'] = df['Arrival_Time'].apply(extract_hour)

# Function to categorize time of day
def time_category(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 20:
        return 'Evening'
    else:
        return 'Night'

# Apply categorization
df['Dep_Time'] = df['Dep_Time'].apply(time_category)
df['Arrival_Time'] = df['Arrival_Time'].apply(time_category)

# Count flights that started in Morning and arrived in Evening
count = df[(df['Dep_Time'] == 'Morning') & (df['Arrival_Time'] == 'Evening')].shape[0]
print("Flights from Morning to Evening:", count)

Flights from Morning to Evening: 922


Encode the values of column 'WeekDay' as follows:
Weekends (Sunday, Saturday) = 1
all remaining five days = 0
What is the most frequent (mode) WeekDay?

In [13]:
# Encode Weekends as 1, Weekdays as 0
df['WeekDay'] = df['WeekDay'].apply(lambda x: 1 if x in ['Saturday', 'Sunday'] else 0)

# Find the most frequent (mode) WeekDay
most_frequent = df['WeekDay'].mode()[0]

if most_frequent == 1:
    print("Most frequent WeekDay: Weekends")
else:
    print("Most frequent WeekDay: Weekdays")


Most frequent WeekDay: Weekdays


In [15]:
from sklearn.datasets import load_iris
data=load_iris()
data.feature_names
data.data.shape

(150, 4)

In [19]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import add_dummy_feature

imp = SimpleImputer(missing_values=np.nan, strategy='median')
X = [[3,8], [1, 4], [8, np.nan]]
print(add_dummy_feature(imp.fit_transform(X)))


[[1. 3. 8.]
 [1. 1. 4.]
 [1. 8. 6.]]


In [20]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

X = np.array([[1], [2], [3]])
ft = FunctionTransformer(np.mean)
ft.fit_transform(X)


np.float64(2.0)

In [21]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler, OrdinalEncoder

X = np.array([[1, 'yes'], [2, 'no'], [3, 'no']])

ct = ColumnTransformer([
    ('scaler', MinMaxScaler(), [0]),
    ('pass', 'passthrough', [0]),
    ('encoder', OrdinalEncoder(), [1])
])

print(ct.fit_transform(X))


[['0.0' '1' '1.0']
 ['0.5' '2' '0.0']
 ['1.0' '3' '0.0']]
